In [1]:
!pip install gdown

In [3]:
!gdown --id 1OtwemNuw0qilXAutyuZEjOscZVKuD7Tv

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1OtwemNuw0qilXAutyuZEjOscZVKuD7Tv
To: /content/NPPE1_ModelBuilding3.csv
100% 1.04M/1.04M [00:00<00:00, 86.6MB/s]


In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('NPPE1_ModelBuilding3.csv')

In [6]:
df.head()

0         1         2         3         4         5         6  \
0  0.087472  0.002829  1.768235  0.188396  0.117071  0.148148  0.478165   
1  0.378379  0.022079  1.115629  0.091974  0.066089  0.851852  0.911759   
2  0.066901  0.003828 -0.536262  0.221188  0.255671  0.296296  0.228024   
3  0.140645  0.011132  1.323366  0.422514  0.153103  0.148148  0.410679   
4  0.144225  0.204918 -0.930790  0.148694  0.177490  0.259259  0.146832   

          7         8         9        10        11   12   13         14  
0  0.720443  0.967195  0.281563  0.428571  0.959596  1.0  0.0  23.358097  
1  0.785321  0.885001  0.424648  0.285714  0.868687  0.0  1.0  17.268768  
2  0.406472  0.980184  0.274376  0.428571  0.767677  0.0  1.0  27.776974  
3  0.200319  0.861371  0.305006  0.142857  0.848485  0.0  1.0  16.121960  
4  0.111429  0.983448  0.286322  0.285714  0.616162  1.0  0.0  23.129426

Split the dataset into train dataset and test dataset in the following manner
	Use train_test_split to split the dataset into train and test dataset with test size equal to 0.3(i.e.30%) and random_state equal to 42. Let other parameters have default values.
	Columns except the last column should be the feature matrix (X_train or X_test)
	Last column will be the label vector.

(Common instructions for Q.2, Q.3 and Q.4)

Train the ridge model on the training data with the following parameters:

alpha = 10
solver = 'saga'
tol = 1e-4
random_state = 42

Enter the value of R2  score on the test dataset.


In [7]:
X = df.iloc[:,:-1]

In [8]:
X

0         1         2         3         4         5         6  \
0     0.087472  0.002829  1.768235  0.188396  0.117071  0.148148  0.478165   
1     0.378379  0.022079  1.115629  0.091974  0.066089  0.851852  0.911759   
2     0.066901  0.003828 -0.536262  0.221188  0.255671  0.296296  0.228024   
3     0.140645  0.011132  1.323366  0.422514  0.153103  0.148148  0.410679   
4     0.144225  0.204918 -0.930790  0.148694  0.177490  0.259259  0.146832   
...        ...       ...       ...       ...       ...       ...       ...   
3995  0.127577  0.752579 -1.094105  0.211838  0.359602  0.148148  0.123572   
3996  0.077051  0.005002 -0.191383  0.480423  0.119767  0.185185  0.388834   
3997  0.086530  0.817630 -1.144875  0.162531  0.435076  0.074074  0.309478   
3998  0.182503  0.016436 -0.162302  0.269231  0.359110  0.185185  0.224930   
3999  0.045044  0.012405  2.555294  0.068771  0.099908  0.222222  0.999837   

             7         8         9        10        11   12   13  
0     0.720443  0.967195  0.281563  0.428571  0.959596  1.0  0.0  
1     0.785321  0.885001  0.424648  0.285714  0.868687  0.0  1.0  
2     0.406472  0.980184  0.274376  0.428571  0.767677  0.0  1.0  
3     0.200319  0.861371  0.305006  0.142857  0.848485  0.0  1.0  
4     0.111429  0.983448  0.286322  0.285714  0.616162  1.0  0.0  
...        ...       ...       ...       ...       ...  ...  ...  
3995  0.530956  0.989831  0.111832  0.571429  0.181818  1.0  0.0  
3996  0.572079  0.994367  0.350004  0.285714  0.393939  1.0  0.0  
3997  0.229333  0.991966  0.056595  0.571429  0.141414  1.0  0.0  
3998  0.516934  0.979605  0.517812  0.428571  0.623289  1.0  0.0  
3999  0.640547  0.995184  0.379420  0.285714  0.808081  1.0  0.0  

[4000 rows x 14 columns]

In [9]:
y = df.iloc[:,-1]

In [10]:
y

0       23.358097
1       17.268768
2       27.776974
3       16.121960
4       23.129426
          ...    
3995    32.086286
3996    25.303902
3997    43.984177
3998    18.419660
3999    20.772547
Name: 14, Length: 4000, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
X_train.shape

(2800, 14)

In [14]:
X_test.shape

(1200, 14)

Train the ridge model on the training data with the following parameters:

alpha = 10 solver = 'saga' tol = 1e-4 random_state = 42

In [15]:
from sklearn.linear_model import Ridge

In [16]:
ridge_model = Ridge(alpha=10, solver='saga', tol=1e-4, random_state=42)

In [17]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10, random_state=42, solver='saga')

In [19]:
y_pred = ridge_model.predict(X_test)

Enter the value of R2 score on the test dataset.

In [20]:
from sklearn.metrics import r2_score

In [21]:
score_r2 = r2_score(y_test, y_pred)
score_r2

0.6613547575262211

What is the index of most important feature? Note the index starts from 0. Ignore the intercept for this question.

In [23]:
coefficients = ridge_model.coef_
coefficients

array([ -0.4825441 ,   3.74601838,  -0.73583331,   0.54199933,
        -9.89014109,   5.80114296,  -5.06099736,  -9.45015598,
         4.73124885, -23.51321982,  11.31863371,   0.49450664,
        -0.89196134,   0.89196134])

In [24]:
abs(coefficients)

array([ 0.4825441 ,  3.74601838,  0.73583331,  0.54199933,  9.89014109,
        5.80114296,  5.06099736,  9.45015598,  4.73124885, 23.51321982,
       11.31863371,  0.49450664,  0.89196134,  0.89196134])

In [26]:
np.argmax(abs(ridge_model.coef_))

9

What is the index of least important feature? Note the index starts from 0. Ignore the intercept for this question.

In [27]:
np.argmin(abs(ridge_model.coef_))

0

Take SGDRegressor(random_state = 42) estimator with GridSearchCV. Hyperparameter tuning to be done over the following parameters:
penalty as ['l1', 'l2']
alpha values as [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
values of tol as [1e-4, 1e-3, 1e-2, 1e-1]
Use cross-validation = 5
Set scoring as neg_mean_absolute_error
Use the best model from above hyper parameter tuning process to answer following questions:

In [28]:
from sklearn.linear_model import SGDRegressor

In [40]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error

In [41]:
params_grid = {
    'penalty': ['l1', 'l2'],
    'alpha': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
    'tol': [1e-4, 1e-3, 1e-1]
}

In [42]:
sgd = SGDRegressor(random_state=42)

In [43]:
grid_search = GridSearchCV(
    param_grid=params_grid,
    estimator=sgd,
    cv=5,
    scoring='neg_mean_absolute_error'
)

In [44]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42),
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'], 'tol': [0.0001, 0.001, 0.1]},
             scoring='neg_mean_absolute_error')

What is the best penalty?

In [45]:
best_parameters = grid_search.best_params_
best_parameters

{'alpha': 0.001, 'penalty': 'l2', 'tol': 0.0001}

What will be value of mean absolute error on the test dataset?

In [48]:
y_pred = grid_search.best_estimator_.predict(X_test)

In [49]:
y_pred2 = grid_search.predict(X_test)

In [50]:
mean_absolute_error(y_test, y_pred)

3.8131121797994014

In [51]:
mean_absolute_error(y_test, y_pred2)

3.8131121797994014

Create a pipeline of the PCA() as transformer and Lasso as an estimator.
Use GridSearchCV for tuning the hyperparameters of the created pipeline on training dataset.
	Values of n_components for PCA to be [0.9, 0.95]
	lasso alpha value to be taken as : [10, 1, 0.01, 0.001]
	scoring : neg_mean_absolute_error.
	Use 5 fold cross validation.
	n_jobs = -1 (negative one) [it helps in using all the computational power to run this job]
(Note: Kindly ignore the warning.)

In [72]:
from sklearn.decomposition import PCA
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [73]:
pipeline = Pipeline([
    ('pca', PCA()),
    ('lasso', Lasso(random_state=42))
])

In [86]:
param_grid = {
    'pca__n_components':[0.9, 0.95],
    'lasso__alpha': [10, 1, 0.01, 0.001]
}

In [87]:
grid_searchlasso = GridSearchCV(
  estimator=pipeline,
  param_grid=param_grid,
  cv=5,
  scoring='neg_mean_absolute_error',
  n_jobs=-1
)

In [88]:
grid_searchlasso.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('pca', PCA()),
                                       ('lasso', Lasso(random_state=42))]),
             n_jobs=-1,
             param_grid={'lasso__alpha': [10, 1, 0.01, 0.001],
                         'pca__n_components': [0.9, 0.95]},
             scoring='neg_mean_absolute_error')

If we fit the pipeline on the training dataset, what will be the R2 score on the test dataset?

In [93]:
y_pred = grid_searchlasso.best_estimator_.predict(X_test)

In [94]:
score_r2lasso = r2_score(y_test, y_pred)
score_r2lasso

0.6288625430197575

How much variance is explained (Eigen value) by the first principle component?

In [95]:
grid_searchlasso.best_estimator_.named_steps['pca'].explained_variance_[0]

1.1635075742239045

Create a pipeline of the PolynomialFeatures as transformer and Lasso as an estimator with the following parameters:
  - For PolynomialFeatures:
    - interaction_only = False
    - degree = 2
  - For Lasso:
    - alpha = 1
    - warm_start = True
    - random state as 0

In [96]:
from sklearn.preprocessing import PolynomialFeatures
pipeline = Pipeline([
    ('polynomial', PolynomialFeatures(degree=2, interaction_only=False)),
    ('lasso', Lasso(alpha=1, warm_start=True, random_state=0))
])

In [97]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('polynomial', PolynomialFeatures()),
                ('lasso', Lasso(alpha=1, random_state=0, warm_start=True))])

Fit the pipeline on the training dataset and find the R2 score on the test dataset.


In [98]:
y_pred = pipeline.predict(X_test)

In [99]:
score_r2poly = r2_score(y_test, y_pred)
score_r2poly

0.157678032410551

If you eliminate 1 feature with recursive feature elimination, which feature will be eliminated?

    Type the index of the eliminated feature (index starts from 0).
    Use

    1

    LinearRegression

     model with default parameters as an estimator.
    Use processed training data.



In [100]:
from sklearn.feature_selection import RFE

In [101]:
from sklearn.linear_model import LinearRegression

In [102]:
rfe = RFE(LinearRegression())

In [103]:
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression())

In [104]:
rfe.ranking_

array([4, 2, 8, 7, 1, 1, 1, 1, 1, 1, 1, 5, 3, 6])