In [1]:
import pandas as pd

In [2]:
!pip install gdown

In [3]:
!gdown --id 1DRtaP8QnU7SFrhMsdR67TBNuq5aOusUe

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1DRtaP8QnU7SFrhMsdR67TBNuq5aOusUe
To: /content/NPPE1_Preprocessing1.csv
100% 799k/799k [00:00<00:00, 60.3MB/s]


In [4]:
import pandas as pd
df = pd.read_csv("NPPE1_Preprocessing1.csv")

In [5]:
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE  
0        NO  
1        NO  
2        NO  
3        NO  
4        NO

How many samples are there in the dataset?

In [6]:
df.shape

(4000, 14)

What is the average house price (in lacs)?

In [7]:
df['PRICE'].mean()

24.355923220694248

How many houses have 5 or more rooms?

In [8]:
(df['RM'] >= 5).sum()

3953

What is the average price of the top 10 most expensive houses (in lacs)?


In [9]:
top10 = df.sort_values(by='PRICE', ascending=False).head(10)
top10.head(10)

CRIM         ZN      INDUS  POLINDEX   RM    AGE       DIS  \
3726  4.182121   0.128554  19.976904  1.528834  9.0   98.0  2.999010   
710   1.367115  91.157423   1.946427  2.082207  9.0   26.0  6.744536   
2154  2.462902   0.519717  19.618883  1.155625  8.0   98.0  3.730228   
1214  8.670738   1.048334  18.896860  0.855754  7.0   90.0  2.308349   
2100  2.020623  20.840060   3.979685  0.722676  9.0   68.0  2.918727   
1842  3.736948  91.232005   1.330772  2.315792  8.0   25.0  6.154232   
461   1.351537   0.387394   6.718154  0.721588  9.0   83.0  3.381742   
2491  7.273518   0.736959  19.113359  0.889621  8.0   98.0  1.690659   
3283  9.337719   0.682025  18.501241  2.902898  8.0  100.0  4.833124   
1583  1.406884   0.371987   3.658770  2.425761  8.0   54.0  3.989640   

      HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
3726             5  403.792223  14.902709  369.329946   6.044069  53.090256   
710              3  198.600753  15.522685  396.200791   3.768782  52.868842   
2154             7  403.898966  14.803860  369.483643   4.101480  52.672568   
1214            25  666.389211  22.339853  348.394147   9.208210  52.444791   
2100             5  265.087230  16.609757  385.024319   7.570250  52.219151   
1842             2  200.264763  13.799503  397.014110   3.663236  52.162506   
461              9  308.444147  17.939000  382.428492   4.635004  52.104771   
2491            25  667.041875  21.218037  393.123380   3.096799  52.077883   
3283            24  666.722393  20.795964  366.397689  12.569632  52.066593   
1583             3  193.146481  18.465143  393.587110   5.843853  51.951657   

     RIVERSIDE  
3726        NO  
710        YES  
2154        NO  
1214       YES  
2100        NO  
1842       YES  
461         NO  
2491       YES  
3283        NO  
1583        NO

In [10]:
avgtop10 = top10['PRICE'].mean()

In [11]:
avgtop10

52.36590175716407

In [12]:
top10new = df['PRICE'].nlargest(10)
top10new

3726    53.090256
710     52.868842
2154    52.672568
1214    52.444791
2100    52.219151
1842    52.162506
461     52.104771
2491    52.077883
3283    52.066593
1583    51.951657
Name: PRICE, dtype: float64

In [14]:
top10new_avg = top10new.mean()
top10new_avg

52.36590175716407

What is the total number of missing or unknown values in the number of rooms feature?

In [15]:
df['RM'].unique()

array([ 6.,  7.,  8.,  9., 10., -1.,  5.,  4., 11.])

In [16]:
missing = df['RM'].isna().sum()
missing

0

In [17]:
implausible = (df['RM'] <= 0).sum()
implausible

40

In [18]:
qmark = (df['RM'] == '?').sum()
qmark

0

What is the total number of missing or unknown values in the age feature?

In [19]:
df['AGE'].unique()

array([ 42.,  63.,  -2.,   9.,  20.,  95.,  35.,  97.,  36.,  78.,  99.,
        96.,  19.,  73.,  86.,  37.,  76.,  50.,  32.,  92., 101.,   8.,
        94.,  84.,  47.,  43.,  65.,  46.,  59.,  74.,  93.,  80.,  98.,
       102.,  56., 100.,  89.,  53.,  18.,  71.,  62.,  83.,  66.,   7.,
        77.,  91.,  90.,  58.,  57.,  60.,  87.,  75.,  34.,  85.,  48.,
        33.,  38.,  30.,  23.,  55.,  11.,  14.,  45.,  41.,  88.,  16.,
        12.,  79.,  67.,  39.,  49.,  61.,  70.,  54.,  10.,  22.,  72.,
        15.,  51.,  81.,  31.,  52.,  44.,  28.,  17.,  40.,  29.,  69.,
        64.,  24.,  82.,  26.,  68.,  27.,  13., 103.,  21.,  25.,   6.,
         5.,   3.,   4.])

In [21]:
df['AGE'].value_counts()[-2]

50

In [22]:
missing_age = df['AGE'].isna().sum()
missing_age

0

In [23]:
missing_age_new = df['AGE'].isnull().sum()
missing_age_new

0

In [24]:
implausible_age = (df['AGE'] <= 0).sum()
implausible_age

50

In [25]:
qmark_age = (df['AGE'] == '?').sum()
qmark_age

0

In [26]:
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE  
0        NO  
1        NO  
2        NO  
3        NO  
4        NO

What is the total number of missing or unknown values in the RIVERSIDE feature?

In [27]:
df['RIVERSIDE'].unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [28]:
df['RIVERSIDE'].value_counts()['UNKNOWN']

88

In [29]:
riverside_miss_unkno = df['RIVERSIDE'].value_counts(dropna=False)
riverside_miss_unkno

RIVERSIDE
NO         3595
YES         317
UNKNOWN      88
Name: count, dtype: int64

How many houses are on riverside and were built within the last 50 years (i.e. a house 50 years old or younger)? For this question, ignore the rows that have missing values in either riverside feature or age feature.

In [117]:
print(df.shape)
clean_df = df.dropna(subset = ['RIVERSIDE','AGE'])
print(clean_df.shape)

(4000, 14)
(4000, 14)


In [118]:
# Drop rows with missing values in RIVERSIDE or age
filtered_df = df.dropna(subset=['RIVERSIDE', 'AGE'])

# Filter for houses on the riverside and with age <= 50 years
houses_recent_riverside = filtered_df[(filtered_df['RIVERSIDE'] == 'YES') & (filtered_df['AGE'] <= 50)]

# Count the resulting houses
count = houses_recent_riverside.shape[0]
print("Number of houses on riverside and built within the last 50 years:", count)


Number of houses on riverside and built within the last 50 years: 53


In [30]:
num_df_filtered = ((df['RIVERSIDE'] == 'YES') & (df['AGE'] <= 50) & (df['AGE'] != -2)).sum()
num_df_filtered

44

In [26]:
num_highway = (df['HIGHWAYCOUNT'].isin([6,7,8])).sum()
num_highway

1211

In [36]:
df[df['HIGHWAYCOUNT'].isin([6,7,8])].shape

(1211, 14)

In [37]:
def get_category(x):
  if x < 10:
    return 'Category 1'
  elif 10 <= x < 20:
    return 'Category 2'
  elif 20 <= x < 30:
    return 'Category 3'
  elif 30 <= x < 40:
    return 'Category 4'
  else:
    return 'Category 5'

In [38]:
df['CATEGORY'] = df['PRICE'].apply(get_category)

In [39]:
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE    CATEGORY  
0        NO  Category 3  
1        NO  Category 3  
2        NO  Category 2  
3        NO  Category 3  
4        NO  Category 3

In [27]:
conditions = [
    (df['PRICE'] < 10),
    ((df['PRICE'] >= 10) & (df['PRICE'] < 20)),
    ((df['PRICE'] >= 20) & (df['PRICE'] < 30)),
    ((df['PRICE'] >= 30) & (df['PRICE'] < 40)),
    (df['PRICE'] >= 40)
]

In [28]:
choices = ['Category 1','Category 2','Category 3','Category 4','Category 5']

In [29]:
import numpy as np
df['CATEGORY'] = np.select(conditions, choices, default = 'Unknown')

In [30]:
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE    CATEGORY  
0        NO  Category 3  
1        NO  Category 3  
2        NO  Category 2  
3        NO  Category 3  
4        NO  Category 3

In [42]:
df['HIGHWAYCOUNT'].unique()

array([ 5,  8, 25,  4,  1,  6,  7,  2, 24,  3, 26, 10,  9, 11, 27])

In [43]:
def get_tier(y):
  if y < 10:
    return 'Tier 3'
  elif 10 >= y < 20:
    return 'Tier 2'
  else:
    return 'Tier 1'

In [44]:
df['TIER'] = df['HIGHWAYCOUNT'].apply(get_tier)

In [45]:
df.head(10)

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   
5  10.024771   0.473322  18.580453  0.970169  6.0  95.0   2.107826   
6   0.649502  96.496960   3.016816  0.976858  9.0  35.0   5.138501   
7   0.712699   0.882697  21.978632  1.186936  7.0  97.0   2.619283   
8   0.413350   1.059814   6.459012  0.804208  6.0  36.0   6.524673   
9   0.636040   0.868701  12.747994  1.865499  8.0  78.0   2.650398   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   
5            25  666.904535  20.498188  397.914396  25.251424  14.049185   
6             6  224.451415  15.696717  392.988429   4.462663  49.868745   
7             4  437.533605  22.235343  388.800277  15.447361  18.564350   
8             7  224.715116  21.605354  397.509751   8.015029  22.566385   
9             2  273.231800  21.100782  398.164093   9.956868  20.688966   

  RIVERSIDE    CATEGORY    TIER  
0        NO  Category 3  Tier 3  
1        NO  Category 3  Tier 3  
2        NO  Category 2  Tier 1  
3        NO  Category 3  Tier 3  
4        NO  Category 3  Tier 3  
5        NO  Category 2  Tier 1  
6        NO  Category 5  Tier 3  
7        NO  Category 2  Tier 3  
8   UNKNOWN  Category 3  Tier 3  
9        NO  Category 3  Tier 3

In [46]:
df['CATEGORY'].value_counts()

CATEGORY
Category 3    2028
Category 2    1158
Category 4     503
Category 5     268
Category 1      43
Name: count, dtype: int64

In [47]:
df.head(10)

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   
5  10.024771   0.473322  18.580453  0.970169  6.0  95.0   2.107826   
6   0.649502  96.496960   3.016816  0.976858  9.0  35.0   5.138501   
7   0.712699   0.882697  21.978632  1.186936  7.0  97.0   2.619283   
8   0.413350   1.059814   6.459012  0.804208  6.0  36.0   6.524673   
9   0.636040   0.868701  12.747994  1.865499  8.0  78.0   2.650398   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   
5            25  666.904535  20.498188  397.914396  25.251424  14.049185   
6             6  224.451415  15.696717  392.988429   4.462663  49.868745   
7             4  437.533605  22.235343  388.800277  15.447361  18.564350   
8             7  224.715116  21.605354  397.509751   8.015029  22.566385   
9             2  273.231800  21.100782  398.164093   9.956868  20.688966   

  RIVERSIDE    CATEGORY    TIER  
0        NO  Category 3  Tier 3  
1        NO  Category 3  Tier 3  
2        NO  Category 2  Tier 1  
3        NO  Category 3  Tier 3  
4        NO  Category 3  Tier 3  
5        NO  Category 2  Tier 1  
6        NO  Category 5  Tier 3  
7        NO  Category 2  Tier 3  
8   UNKNOWN  Category 3  Tier 3  
9        NO  Category 3  Tier 3

 Replace the respective missing or unknown values in features room count, riverside and age with np.nan.

In [49]:
import numpy as np
df['RIVERSIDE'] = df['RIVERSIDE'].replace("UNKNOWN", np.nan)
df.head(10)

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   
5  10.024771   0.473322  18.580453  0.970169  6.0  95.0   2.107826   
6   0.649502  96.496960   3.016816  0.976858  9.0  35.0   5.138501   
7   0.712699   0.882697  21.978632  1.186936  7.0  97.0   2.619283   
8   0.413350   1.059814   6.459012  0.804208  6.0  36.0   6.524673   
9   0.636040   0.868701  12.747994  1.865499  8.0  78.0   2.650398   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   
5            25  666.904535  20.498188  397.914396  25.251424  14.049185   
6             6  224.451415  15.696717  392.988429   4.462663  49.868745   
7             4  437.533605  22.235343  388.800277  15.447361  18.564350   
8             7  224.715116  21.605354  397.509751   8.015029  22.566385   
9             2  273.231800  21.100782  398.164093   9.956868  20.688966   

  RIVERSIDE    CATEGORY    TIER  
0        NO  Category 3  Tier 3  
1        NO  Category 3  Tier 3  
2        NO  Category 2  Tier 1  
3        NO  Category 3  Tier 3  
4        NO  Category 3  Tier 3  
5        NO  Category 2  Tier 1  
6        NO  Category 5  Tier 3  
7        NO  Category 2  Tier 3  
8       NaN  Category 3  Tier 3  
9        NO  Category 3  Tier 3

In [50]:
df['RM'] = df['RM'].replace(0, np.nan)


In [51]:
df['AGE'] = df['AGE'].replace("UNKNOWN",np.nan)

In [54]:
df = df.drop(columns=(['TIER']))

In [55]:
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE    CATEGORY  
0        NO  Category 3  
1        NO  Category 3  
2        NO  Category 2  
3        NO  Category 3  
4        NO  Category 3

In [56]:
from sklearn.model_selection import train_test_split

1. Keep 30% of the data as test set.
2. Use random_state as 0
3. PRICE is the target, rest of the columns are the features.
4. Apply train test split.

In [57]:
X = df.drop(columns = ['PRICE'])
y = df['PRICE']

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [66]:
X_train.shape

(2800, 14)

In [67]:
X_test.shape

(1200, 14)

Apply following preprocessing steps:

1. Drop CATEGORY column
2. CRIM: min max scaling
3. ZN: min max scaling
4. INDUS: standard scaling
5. POLINDEX: min max scaling
6. DIS: min max scaling
7. HIGHWAYCOUNT: min max scaling
8. TAX: min max scaling
9. PTRATIO: min max scaling
10. IMM: min max scaling
11. BPL: min max scaling
12. RM: impute with median then min max scaling
13. AGE: impute with mean then min max scaling
14. RIVERSIDE: Impute with most frequent value then one hot encode.

NOTE:
1. Make sure to preprocess the features in exactly above order. Answer of Q.16 depends upon correct order of featuring processing.
2. You may have to use multiple instances of a trasnformer for this question.



In [68]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

Drop the column 'CATEGORY'

In [69]:
df = df.drop(columns = ['CATEGORY'])
df.head()

KeyError: "['CATEGORY'] not found in axis"

In [70]:
transformer = ColumnTransformer(
    [
        ('mmscaler',MinMaxScaler(), ['CRIM','ZN','POLINDEX','DIS','HIGHWAYCOUNT','TAX','PTRATIO','IMM','BPL']),
        ('INDUS_stdscaler',StandardScaler(),['INDUS']),
        ('RM_pipeline', Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('mm_scaler', MinMaxScaler())
        ]),['RM']),
        ('AGE_pipeline',Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('mm_scaler',MinMaxScaler())
        ]),['AGE']),
        ('RIVERSIDE', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ("encoder", OneHotEncoder())
        ]),["RIVERSIDE"])
    ],
    remainder="passthrough"
)
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('mmscaler', MinMaxScaler(),
                                 ['CRIM', 'ZN', 'POLINDEX', 'DIS',
                                  'HIGHWAYCOUNT', 'TAX', 'PTRATIO', 'IMM',
                                  'BPL']),
                                ('INDUS_stdscaler', StandardScaler(),
                                 ['INDUS']),
                                ('RM_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('mm_scaler',
                                                  MinMaxScaler())]),
                                 ['RM']),
                                ('AGE_pipeline',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('mm_scaler',
                                                  MinMaxScaler())]),
                                 ['AGE']),
                                ('RIVERSIDE',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder', OneHotEncoder())]),
                                 ['RIVERSIDE'])])

In [71]:
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)
X_train.shape

(2800, 15)

CRIM: min max scaling

In [60]:
MinMaxScaler().fit_transform(df[['CRIM']])

array([[0.07909526],
       [0.06490115],
       [0.86547041],
       ...,
       [0.06580511],
       [0.04421466],
       [0.40614925]])

In [61]:
type(df['CRIM'])

pandas.core.series.Series

ZN: min max scaling

In [62]:
MinMaxScaler().fit_transform(df[['ZN']])

array([[1.40527806e-02],
       [2.51067584e-03],
       [4.33499295e-03],
       ...,
       [2.08532550e-01],
       [4.46536541e-01],
       [6.28052031e-06]])

INDUS: standard scaling

In [64]:
StandardScaler().fit_transform(df[['INDUS']])

array([[-0.49181501],
       [-0.72441309],
       [ 1.04212217],
       ...,
       [-1.04158635],
       [-1.09900292],
       [ 1.08263728]])

POLINDEX: min max scaling

In [65]:
MinMaxScaler().fit_transform(df[['POLINDEX']])

array([[0.19435802],
       [0.22415346],
       [0.64501063],
       ...,
       [0.1964778 ],
       [0.35031934],
       [0.12238168]])

DIS: min max scaling

In [68]:
MinMaxScaler().fit_transform(df[['DIS']])

array([[0.31740055],
       [0.24393777],
       [0.09675441],
       ...,
       [0.07954095],
       [0.50208918],
       [0.19852465]])

HIGHWAYCOUNT: min max scaling

In [66]:
MinMaxScaler().fit_transform(df[['HIGHWAYCOUNT']])

array([[0.15384615],
       [0.26923077],
       [0.92307692],
       ...,
       [0.23076923],
       [0.19230769],
       [0.88461538]])

TAX: min max scaling

In [67]:
MinMaxScaler().fit_transform(df[['TAX']])

array([[0.17523887],
       [0.22893296],
       [0.91153062],
       ...,
       [0.14646674],
       [0.40225678],
       [0.91171052]])

PTRATIO: min max scaling

In [69]:
MinMaxScaler().fit_transform(df[['PTRATIO']])

array([[0.68900297],
       [0.41296404],
       [0.66006632],
       ...,
       [0.16822105],
       [0.34939221],
       [0.83741712]])

IMM: min max scaling

In [70]:
MinMaxScaler().fit_transform(df[['IMM']])

array([[0.99508149],
       [0.94096921],
       [0.96572315],
       ...,
       [0.97830208],
       [0.94491967],
       [0.97944137]])

BPL: min max scaling

In [71]:
MinMaxScaler().fit_transform(df[['BPL']])

array([[0.24918892],
       [0.28324361],
       [0.51100474],
       ...,
       [0.16710883],
       [0.12873341],
       [0.3765623 ]])

RM: impute with median then min max scaling

In [72]:
imputer_rm = SimpleImputer(strategy='median')
df['RM'] = imputer_rm.fit_transform(df[['RM']])
df['RM'] = MinMaxScaler().fit_transform(df[['RM']])

In [73]:
df['RM']

0       0.583333
1       0.666667
2       0.750000
3       0.583333
4       0.750000
          ...   
3995    0.583333
3996    0.583333
3997    0.666667
3998    0.750000
3999    0.666667
Name: RM, Length: 4000, dtype: float64

AGE: impute with mean then min max scaling

In [74]:
impute_age = SimpleImputer(strategy='median')
df['AGE'] = impute_age.fit_transform(df[['AGE']])
df['AGE'] = MinMaxScaler().fit_transform(df[['AGE']])

In [75]:
df['AGE']

0       0.419048
1       0.619048
2       0.000000
3       0.104762
4       0.209524
          ...   
3995    0.933333
3996    0.971429
3997    0.990476
3998    0.228571
3999    0.866667
Name: AGE, Length: 4000, dtype: float64

RIVERSIDE: Impute with most frequent value then one hot encode.

In [76]:
df.head(20)

CRIM         ZN      INDUS  POLINDEX        RM       AGE        DIS  \
0    1.026769   1.429034   7.851300  1.134216  0.583333  0.419048   5.251911   
1    0.848089   0.255543   6.263434  1.245993  0.666667  0.619048   4.305546   
2   10.925905   0.441022  18.322960  2.824833  0.750000  0.000000   2.409495   
3    0.559027   1.041175  11.114920  0.794952  0.583333  0.104762   6.898669   
4    0.905063  81.167963   3.673369  1.029030  0.750000  0.209524  10.246463   
5   10.024771   0.473322  18.580453  0.970169  0.583333  0.923810   2.107826   
6    0.649502  96.496960   3.016816  0.976858  0.833333  0.352381   5.138501   
7    0.712699   0.882697  21.978632  1.186936  0.666667  0.942857   2.619283   
8    0.413350   1.059814   6.459012  0.804208  0.583333  0.361905   6.524673   
9    0.636040   0.868701  12.747994  1.865499  0.750000  0.761905   2.650398   
10   3.304369   0.490087  20.062733  2.278768  0.583333  0.961905   1.391987   
11   1.656863   0.263417  22.617375  1.605176  0.583333  0.933333   2.691196   
12   0.178938   0.107933  11.382230  1.136220  0.583333  0.200000   8.312420   
13   1.085613   2.401877   7.568410  1.132762  0.750000  0.714286   4.719883   
14  11.115367   1.154237  18.338321  1.533564  0.666667  0.838095   2.808840   
15   0.886025  21.990581   3.676025  1.326340  0.750000  0.371429   5.564576   
16   0.115406   1.515490   4.655417  0.512364  0.666667  0.742857   3.199696   
17   0.342595  41.179260   7.072400  0.556617  0.833333  0.495238   5.349678   
18   0.693664  81.620501   3.904568  0.813763  0.750000  0.323810   9.480578   
19   4.406295   1.121569  20.737598  0.876251  0.750000  0.895238   3.449279   

    HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0              5  279.201277  20.689586  398.811960  10.461456  22.991633   
1              8  307.444529  17.465398  377.153649  11.619690  24.551055   
2             25  666.492973  20.351601  387.061355  19.366070  15.875346   
3              4  305.514181  19.787314  391.778647   6.206820  23.007756   
4              1  315.913960  17.360439  395.833166  10.827105  21.503177   
5             25  666.904535  20.498188  397.914396  25.251424  14.049185   
6              6  224.451415  15.696717  392.988429   4.462663  49.868745   
7              4  437.533605  22.235343  388.800277  15.447361  18.564350   
8              7  224.715116  21.605354  397.509751   8.015029  22.566385   
9              2  273.231800  21.100782  398.164093   9.956868  20.688966   
10             6  403.100369  15.056411  397.195045  30.285161  12.264939   
11             6  437.463750  21.591753  398.755804  18.370540  16.063960   
12             4  306.240238  21.189061  377.250445  10.778848  22.076675   
13             8  308.412421  19.102945  391.312384   5.779034  31.943051   
14            24  667.373943  20.560107   83.561491  17.909382  16.244298   
15             6  217.050191  15.049440  394.023514   5.166237  37.209641   
16             6  297.105276  18.211377  392.698247   7.489230  30.456459   
17             5  255.681325  17.777796  390.376446   6.103957  33.451565   
18             2  315.122585  16.928254  393.246363   7.280530  22.067786   
19            25  666.135487  20.390988  391.655580  13.606076  21.847968   

   RIVERSIDE  
0         NO  
1         NO  
2         NO  
3         NO  
4         NO  
5         NO  
6         NO  
7         NO  
8        NaN  
9         NO  
10       NaN  
11        NO  
12        NO  
13        NO  
14        NO  
15        NO  
16        NO  
17       YES  
18        NO  
19       YES

In [82]:
imputer_riverside = SimpleImputer(strategy = 'most_frequent')
df['RIVERSIDE'] = imputer_riverside.fit_transform(df[['RIVERSIDE']]).ravel()
df = pd.get_dummies(df, columns=['RIVERSIDE'], prefix='RIVERSIDE')

In [83]:
df.head()

CRIM         ZN      INDUS  POLINDEX        RM       AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  0.583333  0.419048   5.251911   
1   0.848089   0.255543   6.263434  1.245993  0.666667  0.619048   4.305546   
2  10.925905   0.441022  18.322960  2.824833  0.750000  0.000000   2.409495   
3   0.559027   1.041175  11.114920  0.794952  0.583333  0.104762   6.898669   
4   0.905063  81.167963   3.673369  1.029030  0.750000  0.209524  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

   RIVERSIDE_NO  RIVERSIDE_YES  
0          True          False  
1          True          False  
2          True          False  
3          True          False  
4          True          False

In [84]:
df.shape

(4000, 15)

Find the mean of feature values of test

In [86]:
mean_X_test = X_test.values.mean()

In [87]:
mean_X_test

24.461955181059775

In [88]:
df

CRIM         ZN      INDUS  POLINDEX        RM       AGE  \
0      1.026769   1.429034   7.851300  1.134216  0.583333  0.419048   
1      0.848089   0.255543   6.263434  1.245993  0.666667  0.619048   
2     10.925905   0.441022  18.322960  2.824833  0.750000  0.000000   
3      0.559027   1.041175  11.114920  0.794952  0.583333  0.104762   
4      0.905063  81.167963   3.673369  1.029030  0.750000  0.209524   
...         ...        ...        ...       ...       ...       ...   
3995   4.366543   1.159592  22.230240  1.146936  0.583333  0.933333   
3996   9.132894   0.294115  18.741019  0.876901  0.583333  0.971429   
3997   0.859468  21.201881   4.098201  1.142168  0.666667  0.990476   
3998   0.587681  45.399856   3.706238  1.719303  0.750000  0.228571   
3999   5.143827   0.000920  18.599543  0.864198  0.666667  0.866667   

            DIS  HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL  \
0      5.251911             5  279.201277  20.689586  398.811960  10.461456   
1      4.305546             8  307.444529  17.465398  377.153649  11.619690   
2      2.409495            25  666.492973  20.351601  387.061355  19.366070   
3      6.898669             4  305.514181  19.787314  391.778647   6.206820   
4     10.246463             1  315.913960  17.360439  395.833166  10.827105   
...         ...           ...         ...        ...         ...        ...   
3995   2.332414             6  403.809266  15.810504  354.065893  21.902957   
3996   2.509486            24  666.000417  20.548310  394.997535  19.940826   
3997   2.187747             7  264.067049  14.606753  392.096041   7.669832   
3998   7.631113             6  398.613388  16.722867  378.734812   6.364646   
3999   3.720523            24  666.587599  22.423092  392.552040  14.793550   

          PRICE  RIVERSIDE_NO  RIVERSIDE_YES  
0     22.991633          True          False  
1     24.551055          True          False  
2     15.875346          True          False  
3     23.007756          True          False  
4     21.503177          True          False  
...         ...           ...            ...  
3995  16.375222          True          False  
3996   9.565996          True          False  
3997  30.106096          True          False  
3998  37.403409          True          False  
3999  20.204362          True          False  

[4000 rows x 15 columns]

In [89]:
df_train, df_test = train_test_split(df, test_size=0.3, random_state=0)

# Compute the mean of the test set (features only)
# Assuming PRICE is the target, drop it if needed:
test_features = df_test.drop(columns=['PRICE'])
mean_test = test_features.values.mean()
print("Mean of transformed test data:", mean_test)

Mean of transformed test data: 58.772991274171815
